"""Generate `docs/ASSUMPTIONS.md` from the parameter files.

The brief asks submissions to distinguish supplied data, measured data,
assumptions and invented values. Writing that by hand guarantees it drifts from
the code within a week. Instead every parameter declares its own provenance in
YAML and this module renders the ledger, so the document cannot disagree with
what the models actually use.

Run via `python -m sfp.cli assumptions`.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from sfp.params import PROVENANCE_LEVELS, ParamSet, load_all, provenance_summary

PROVENANCE_BLURB = {
    "supplied": "Given by the challenge brief, or a design input chosen by the user at run time.",
    "measured": "Taken from a real dataset. Traceable to a named source.",
    "literature": "Taken from a cited publication. The citation is recorded with the value.",
    "assumed": "Engineering judgement. Defensible and order-of-magnitude right, but not sourced.",
    "invented": "Placeholder with no external basis. Treat any result that is sensitive to these with suspicion.",
}

HEADER = """# Assumptions ledger

*Generated by `python -m sfp.cli assumptions` on {today}. Do not edit by hand --
edit the YAML in `sfp/models/params/` and regenerate.*

The challenge brief asks entrants to distinguish supplied data, measured data,
assumptions and invented values. Every numerical parameter in this project
carries a provenance tag in its definition, and this file is rendered from those
tags. If a number is used by a model, it appears below.

## Provenance levels

{levels}

## Summary

{summary}

{caveat}
"""

CAVEAT = """## What this ledger does not cover

Three classes of assumption are structural rather than numerical, and so cannot
be tagged on a parameter. They are recorded here explicitly:

1. **Model form.** Each subsystem is a lumped, control-oriented reduced-order
   model, not a distributed one. The choice of *which* physics to keep is itself
   an assumption; the rationale is documented in each module's docstring, with
   the source paper named.

2. **Calcium looping at ambient CO2 partial pressure.** The dynamic Ca-looping
   model this project draws on (Cormos & Simon, 2013) is a post-combustion
   model, where CO2 is a percent-level fraction of the gas. Direct air capture
   works at 420 ppm, where carbonation kinetics are far slower -- which is why
   real systems such as Carbon Engineering's put a KOH contactor and causticiser
   upstream of the CaCO3/CaO loop rather than contacting CaO with air directly.
   The brief specifies calcium looping, so it is modelled as specified, with the
   rate constants reparameterised for ambient partial pressure. Any absolute
   capture rate from this model should be read as indicative.

3. **Weather provenance is per-run, not global.** PVGIS TMY data is `measured`;
   the offline synthetic fallback is `invented`. Every run records which it used
   and the report prints it. A result generated on synthetic weather is not a
   result about a real site.
"""


def _format_levels() -> str:
    lines = []
    for level in PROVENANCE_LEVELS:
        lines.append(f"- **`{level}`** -- {PROVENANCE_BLURB[level]}")
    return "\n".join(lines)


def _format_summary(sets: dict[str, ParamSet]) -> str:
    counts = provenance_summary(sets)
    total = sum(counts.values())
    lines = ["| Provenance | Count | Share |", "| --- | ---: | ---: |"]
    for level in PROVENANCE_LEVELS:
        n = counts[level]
        share = f"{100.0 * n / total:.0f} %" if total else "-"
        lines.append(f"| `{level}` | {n} | {share} |")
    lines.append(f"| **total** | **{total}** | |")
    return "\n".join(lines)


def _format_group(ps: ParamSet) -> str:
    lines = [f"### `{ps.name}`", ""]
    if ps.description:
        lines.extend([ps.description.strip(), ""])
    lines.append("| Parameter | Value | Units | Provenance | Source / note |")
    lines.append("| --- | ---: | --- | --- | --- |")
    for p in sorted(ps, key=lambda q: (PROVENANCE_LEVELS.index(q.provenance), q.name)):
        detail = p.source or p.note
        if p.source and p.note:
            detail = f"{p.source}. {p.note}"
        detail = " ".join(detail.split())
        if p.uncertain:
            detail += f" *(perturbed in the truth simulator, sigma={p.sigma:.0%})*"
        value = f"{p.value:g}"
        lines.append(f"| `{p.name}` | {value} | {p.units} | `{p.provenance}` | {detail} |")
    lines.append("")
    return "\n".join(lines)


def render(sets: dict[str, ParamSet] | None = None) -> str:
    """The full ledger as markdown."""
    sets = sets or load_all()
    body = [
        HEADER.format(
            today=date.today().isoformat(),
            levels=_format_levels(),
            summary=_format_summary(sets),
            caveat=CAVEAT,
        ),
        "## Parameters by subsystem",
        "",
    ]
    for name in sorted(sets):
        body.append(_format_group(sets[name]))
    return "\n".join(body)


def write(path: Path | None = None) -> Path:
    """Render the ledger to `docs/ASSUMPTIONS.md` and return the path written."""
    path = path or Path(__file__).resolve().parents[2] / "docs" / "ASSUMPTIONS.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")
    return path
